import { writeFile } from "node:fs/promises";
import type { ColorHex, Colors, SemanticTokenColors, Theme, TokenColors } from "./types";

const opacity = {
  transparent: 0,
  subtle: 0.25,
  medium: 0.5,
  strong: 0.75,
  opaque: 1,
} as const;

function setAlpha(color: ColorHex, alpha: number): ColorHex {
  const a = Math.round(alpha * 255);
  return `${color}${a.toString(16).padStart(2, "0")}`;
}

const palette = {
  mist: {
    bgDark: "#090b0c",
    bg: "#161b1d",
    border: "#22292b",
    selection: "#394447",
    foreground: "#9ca8ab",
    emphasisForeground: "#e3e7e8",
  },
  primary: {
    dark: "#0092b8",
    light: "#00d3f2",
  },
  secondary: {
    dark: "#c70036",
    light: "#ff637e",
  },
  git: {
    added: "#00d492",
    deleted: "#ff637e",
    conflicting: "#ff8904",
    ignored: "#67787c",
    modified: "#51a2ff",
    renamed: "#7f22fe",
    stageDeleted: "#c70036",
    stageModified: "#155dfc",
    submodule: "#0092b8",
    untracked: "#009966",
  },
  accent: {
    orange: {
      dark: "#f54a00",
      light: "#ff8904",
    },
    amber: {
      dark: "#e17100",
      light: "#ffba00",
    },
    emerald: {
      dark: "#009966",
      light: "#00d492",
    },
    cyan: {
      dark: "#0092b8",
      light: "#00d3f2",
    },
    blue: {
      dark: "#155dfc",
      light: "#51a2ff",
    },
    violet: {
      dark: "#7f22fe",
      light: "#a684ff",
    },
    rose: {
      dark: "#c70036",
      light: "#ff637e",
    },
  },
} as const;

const colors: Colors = {
  "actionBar.toggledBackground": palette.mist.bg,
  "activityBar.activeBackground": palette.mist.bg,
  "activityBar.activeBorder": palette.mist.border,
  "activityBar.activeFocusBorder": palette.mist.border,
  "activityBar.background": palette.mist.bg,
  "activityBar.border": palette.mist.border,
  "activityBar.dropBorder": palette.mist.border,
  "activityBar.foreground": palette.mist.foreground,
  "activityBar.inactiveForeground": palette.git.ignored,
  "activityBarBadge.background": palette.mist.bg,
  "activityBarBadge.foreground": palette.mist.emphasisForeground,
  "activityBarTop.activeBackground": palette.mist.bg,
  "activityBarTop.activeBorder": palette.mist.border,
  "activityBarTop.background": palette.mist.bg,
  "activityBarTop.dropBorder": palette.mist.border,
  "activityBarTop.foreground": palette.mist.emphasisForeground,
  "activityBarTop.inactiveForeground": palette.mist.emphasisForeground,
  "activityErrorBadge.background": setAlpha(palette.secondary.dark, opacity.medium),
  "activityErrorBadge.foreground": palette.secondary.light,
  "activityWarningBadge.background": setAlpha(palette.accent.amber.dark, opacity.subtle),
  "activityWarningBadge.foreground": palette.accent.amber.light,
  "badge.background": palette.mist.bg,
  "badge.foreground": palette.mist.emphasisForeground,
  "banner.background": palette.mist.bg,
  "banner.foreground": palette.mist.foreground,
  "banner.iconForeground": palette.mist.foreground,
  "breadcrumb.activeSelectionForeground": palette.mist.emphasisForeground,
  "breadcrumb.background": palette.mist.bgDark,
  "breadcrumb.focusForeground": palette.mist.emphasisForeground,
  "breadcrumb.foreground": palette.mist.emphasisForeground,
  "breadcrumbPicker.background": palette.mist.bg,
  "button.background": palette.primary.dark,
  "button.border": palette.primary.dark,
  "button.foreground": palette.mist.emphasisForeground,
  "button.hoverBackground": palette.primary.dark,
  "button.secondaryBackground": palette.primary.dark,
  "button.secondaryForeground": palette.mist.emphasisForeground,
  "button.secondaryHoverBackground": palette.primary.dark,
  "button.separator": palette.mist.border,
  "chart.axis": palette.accent.violet.light,
  "chart.guide": palette.secondary.light,
  "chart.line": palette.accent.violet.light,
  "charts.blue": palette.accent.blue.light,
  "charts.foreground": palette.mist.foreground,
  "charts.green": palette.accent.emerald.light,
  "charts.lines": palette.mist.foreground,
  "charts.orange": palette.accent.orange.light,
  "charts.purple": palette.accent.violet.light,
  "charts.red": palette.secondary.light,
  "charts.yellow": palette.accent.amber.light,
  "chat.avatarBackground": palette.mist.bg,
  "chat.avatarForeground": palette.mist.emphasisForeground,
  "chat.editedFileForeground": palette.mist.emphasisForeground,
  "chat.requestBackground": palette.mist.bg,
  "chat.requestBorder": palette.mist.border,
  "chat.slashCommandBackground": palette.mist.bg,
  "chat.slashCommandForeground": palette.mist.emphasisForeground,
  "checkbox.background": palette.mist.bg,
  "checkbox.border": palette.mist.border,
  "checkbox.foreground": palette.mist.emphasisForeground,
  "checkbox.selectBackground": palette.mist.bg,
  "checkbox.selectBorder": palette.mist.border,
  "commandCenter.activeBackground": palette.mist.bg,
  "commandCenter.activeBorder": palette.mist.border,
  "commandCenter.activeForeground": palette.mist.foreground,
  "commandCenter.background": palette.mist.bg,
  "commandCenter.border": palette.mist.border,
  "commandCenter.debuggingBackground": setAlpha(palette.mist.bg, opacity.medium),
  "commandCenter.foreground": palette.mist.foreground,
  "commandCenter.inactiveBorder": palette.mist.border,
  "commandCenter.inactiveForeground": palette.mist.foreground,
  "commentsView.resolvedIcon": palette.git.ignored,
  "commentsView.unresolvedIcon": palette.git.ignored,
  contrastActiveBorder: setAlpha(palette.mist.bgDark, opacity.transparent),
  contrastBorder: palette.mist.selection,
  "debugConsole.errorForeground": palette.secondary.light,
  "debugConsole.infoForeground": palette.primary.light,
  "debugConsole.sourceForeground": palette.accent.amber.light,
  "debugConsole.warningForeground": palette.accent.amber.light,
  "debugConsoleInputIcon.foreground": palette.accent.amber.light,
  "debugExceptionWidget.background": setAlpha(palette.accent.amber.dark, opacity.subtle),
  "debugExceptionWidget.border": palette.mist.border,
  "debugIcon.breakpointCurrentStackframeForeground": palette.accent.amber.light,
  "debugIcon.breakpointDisabledForeground": palette.accent.amber.light,
  "debugIcon.breakpointForeground": palette.accent.amber.light,
  "debugIcon.breakpointStackframeForeground": palette.accent.amber.light,
  "debugIcon.breakpointUnverifiedForeground": palette.accent.amber.light,
  "debugIcon.continueForeground": palette.accent.amber.light,
  "debugIcon.disconnectForeground": palette.accent.amber.light,
  "debugIcon.pauseForeground": palette.accent.amber.light,
  "debugIcon.restartForeground": palette.accent.amber.light,
  "debugIcon.startForeground": palette.accent.amber.light,
  "debugIcon.stepBackForeground": palette.accent.amber.light,
  "debugIcon.stepIntoForeground": palette.accent.amber.light,
  "debugIcon.stepOutForeground": palette.accent.amber.light,
  "debugIcon.stepOverForeground": palette.accent.amber.light,
  "debugIcon.stopForeground": palette.accent.amber.light,
  "debugTokenExpression.boolean": palette.git.ignored,
  "debugTokenExpression.error": palette.git.ignored,
  "debugTokenExpression.name": palette.git.ignored,
  "debugTokenExpression.number": palette.git.ignored,
  "debugTokenExpression.string": palette.git.ignored,
  "debugTokenExpression.type": palette.git.ignored,
  "debugTokenExpression.value": palette.git.ignored,
  "debugToolBar.background": setAlpha(palette.accent.amber.dark, opacity.subtle),
  "debugToolBar.border": palette.mist.border,
  "debugView.exceptionLabelBackground": setAlpha(palette.accent.amber.dark, opacity.subtle),
  "debugView.exceptionLabelForeground": palette.accent.amber.light,
  "debugView.stateLabelBackground": setAlpha(palette.accent.amber.dark, opacity.subtle),
  "debugView.stateLabelForeground": palette.accent.amber.light,
  "debugView.valueChangedHighlight": palette.git.ignored,
  descriptionForeground: palette.mist.foreground,
  "diffEditor.border": palette.mist.border,
  "diffEditor.diagonalFill": palette.git.ignored,
  "diffEditor.insertedLineBackground": setAlpha(palette.accent.emerald.dark, opacity.subtle),
  "diffEditor.insertedTextBackground": setAlpha(palette.accent.emerald.dark, opacity.subtle),
  "diffEditor.insertedTextBorder": palette.accent.emerald.dark,
  "diffEditor.move.border": palette.mist.border,
  "diffEditor.moveActive.border": palette.mist.border,
  "diffEditor.removedLineBackground": setAlpha(palette.secondary.dark, opacity.medium),
  "diffEditor.removedTextBackground": setAlpha(palette.secondary.dark, opacity.medium),
  "diffEditor.removedTextBorder": palette.secondary.dark,
  "diffEditor.unchangedCodeBackground": palette.mist.bg,
  "diffEditor.unchangedRegionBackground": palette.mist.bg,
  "diffEditor.unchangedRegionForeground": palette.mist.emphasisForeground,
  "diffEditor.unchangedRegionShadow": setAlpha(palette.mist.bgDark, opacity.medium),
  "diffEditorGutter.insertedLineBackground": setAlpha(palette.accent.emerald.dark, opacity.subtle),
  "diffEditorGutter.removedLineBackground": setAlpha(palette.secondary.dark, opacity.medium),
  "diffEditorOverview.insertedForeground": palette.accent.emerald.light,
  "diffEditorOverview.removedForeground": palette.secondary.light,
  disabledForeground: palette.git.ignored,
  "dropdown.background": palette.mist.bg,
  "dropdown.border": palette.mist.border,
  "dropdown.foreground": palette.mist.emphasisForeground,
  "dropdown.listBackground": palette.mist.bg,
  "editor.background": palette.mist.bgDark,
  "editor.compositionBorder": palette.mist.selection,
  "editor.findMatchBackground": setAlpha(palette.primary.dark, opacity.strong),
  "editor.findMatchBorder": palette.primary.dark,
  "editor.findMatchForeground": palette.primary.light,
  "editor.findMatchHighlightBackground": setAlpha(palette.git.ignored, opacity.strong),
  "editor.findMatchHighlightBorder": setAlpha(palette.primary.dark, opacity.medium),
  "editor.findMatchHighlightForeground": setAlpha(palette.primary.dark, opacity.medium),
  "editor.findRangeHighlightBackground": setAlpha(palette.primary.dark, opacity.medium),
  "editor.findRangeHighlightBorder": setAlpha(palette.primary.dark, opacity.medium),
  "editor.focusedStackFrameHighlightBackground": setAlpha(palette.mist.bg, opacity.strong),
  "editor.foldBackground": setAlpha(palette.mist.bgDark, opacity.medium),
  "editor.foldPlaceholderForeground": palette.mist.emphasisForeground,
  "editor.foreground": palette.mist.emphasisForeground,
  "editor.hoverHighlightBackground": setAlpha(palette.mist.bg, opacity.strong),
  "editor.inactiveSelectionBackground": setAlpha(palette.mist.selection, opacity.subtle),
  "editor.inlineValuesBackground": setAlpha(palette.mist.bg, opacity.strong),
  "editor.inlineValuesForeground": palette.mist.emphasisForeground,
  "editor.lineHighlightBackground": setAlpha(palette.mist.bg, opacity.strong),
  "editor.lineHighlightBorder": palette.mist.selection,
  "editor.linkedEditingBackground": palette.mist.bgDark,
  "editor.placeholder.foreground": palette.mist.emphasisForeground,
  "editor.rangeHighlightBackground": setAlpha(palette.mist.bg, opacity.strong),
  "editor.rangeHighlightBorder": palette.mist.selection,
  "editor.selectionBackground": setAlpha(palette.mist.selection, opacity.strong),
  "editor.selectionForeground": setAlpha(palette.mist.bgDark, opacity.transparent),
  "editor.selectionHighlightBackground": setAlpha(palette.mist.selection, opacity.strong),
  "editor.selectionHighlightBorder": palette.mist.selection,
  "editor.snippetFinalTabstopHighlightBackground": setAlpha(palette.mist.bg, opacity.strong),
  "editor.snippetFinalTabstopHighlightBorder": palette.mist.selection,
  "editor.snippetTabstopHighlightBackground": setAlpha(palette.mist.bg, opacity.strong),
  "editor.snippetTabstopHighlightBorder": palette.mist.selection,
  "editor.stackFrameHighlightBackground": setAlpha(palette.mist.bg, opacity.strong),
  "editor.symbolHighlightBackground": setAlpha(palette.mist.bg, opacity.strong),
  "editor.symbolHighlightBorder": palette.mist.selection,
  "editor.wordHighlightBackground": setAlpha(palette.mist.bg, opacity.strong),
  "editor.wordHighlightBorder": palette.mist.selection,
  "editor.wordHighlightStrongBackground": setAlpha(palette.mist.bg, opacity.strong),
  "editor.wordHighlightStrongBorder": palette.mist.selection,
  "editor.wordHighlightTextBackground": setAlpha(palette.mist.bg, opacity.strong),
  "editor.wordHighlightTextBorder": palette.mist.selection,
  "editorActionList.background": palette.mist.bg,
  "editorActionList.focusBackground": palette.mist.bg,
  "editorActionList.focusForeground": palette.mist.emphasisForeground,
  "editorActionList.foreground": palette.mist.emphasisForeground,
  "editorBracketHighlight.foreground1": palette.primary.light,
  "editorBracketHighlight.foreground2": palette.accent.emerald.light,
  "editorBracketHighlight.foreground3": palette.accent.amber.light,
  "editorBracketHighlight.foreground4": palette.primary.light,
  "editorBracketHighlight.foreground5": palette.accent.emerald.light,
  "editorBracketHighlight.foreground6": palette.accent.amber.light,
  "editorBracketHighlight.unexpectedBracket.foreground": palette.secondary.light,
  "editorBracketMatch.background": setAlpha(palette.primary.dark, opacity.medium),
  "editorBracketMatch.border": palette.primary.dark,
  "editorBracketPairGuide.activeBackground1": palette.mist.bgDark,
  "editorBracketPairGuide.activeBackground2": palette.mist.bgDark,
  "editorBracketPairGuide.activeBackground3": palette.mist.bgDark,
  "editorBracketPairGuide.activeBackground4": palette.mist.bgDark,
  "editorBracketPairGuide.activeBackground5": palette.mist.bgDark,
  "editorBracketPairGuide.activeBackground6": palette.mist.bgDark,
  "editorBracketPairGuide.background1": palette.mist.bgDark,
  "editorBracketPairGuide.background2": palette.mist.bgDark,
  "editorBracketPairGuide.background3": palette.mist.bgDark,
  "editorBracketPairGuide.background4": palette.mist.bgDark,
  "editorBracketPairGuide.background5": palette.mist.bgDark,
  "editorBracketPairGuide.background6": palette.mist.bgDark,
  "editorCodeLens.foreground": palette.mist.emphasisForeground,
  "editorCommentsWidget.rangeActiveBackground": palette.mist.bgDark,
  "editorCommentsWidget.rangeBackground": palette.mist.bgDark,
  "editorCommentsWidget.replyInputBackground": palette.mist.bgDark,
  "editorCommentsWidget.resolvedBorder": palette.mist.selection,
  "editorCommentsWidget.unresolvedBorder": palette.mist.selection,
  "editorCursor.background": palette.mist.bgDark,
  "editorCursor.foreground": palette.mist.emphasisForeground,
  "editorError.background": setAlpha(palette.secondary.dark, opacity.medium),
  "editorError.border": palette.secondary.dark,
  "editorError.foreground": palette.secondary.light,
  "editorGhostText.background": palette.mist.bgDark,
  "editorGhostText.border": palette.mist.selection,
  "editorGhostText.foreground": palette.mist.emphasisForeground,
  "editorGroup.border": palette.mist.border,
  "editorGroup.dropBackground": palette.mist.bgDark,
  "editorGroup.dropIntoPromptBackground": palette.mist.bgDark,
  "editorGroup.dropIntoPromptBorder": palette.mist.selection,
  "editorGroup.dropIntoPromptForeground": palette.mist.emphasisForeground,
  "editorGroup.emptyBackground": palette.mist.bgDark,
  "editorGroup.focusedEmptyBorder": palette.mist.selection,
  "editorGroupHeader.border": setAlpha(palette.mist.bgDark, opacity.transparent),
  "editorGroupHeader.noTabsBackground": palette.mist.bgDark,
  "editorGroupHeader.tabsBackground": palette.mist.bg,
  "editorGroupHeader.tabsBorder": palette.mist.selection,
  "editorGutter.addedBackground": setAlpha(palette.accent.emerald.dark, opacity.subtle),
  "editorGutter.background": palette.mist.bgDark,
  "editorGutter.commentGlyphForeground": palette.mist.emphasisForeground,
  "editorGutter.commentRangeForeground": palette.mist.emphasisForeground,
  "editorGutter.commentUnresolvedGlyphForeground": palette.mist.emphasisForeground,
  "editorGutter.deletedBackground": setAlpha(palette.secondary.dark, opacity.medium),
  "editorGutter.foldingControlForeground": palette.mist.emphasisForeground,
  "editorGutter.itemBackground": palette.mist.bgDark,
  "editorGutter.itemGlyphForeground": palette.mist.emphasisForeground,
  "editorGutter.modifiedBackground": setAlpha(palette.accent.blue.dark, opacity.subtle),
  "editorHint.border": palette.primary.dark,
  "editorHint.foreground": palette.primary.light,
  "editorHoverWidget.background": palette.mist.bgDark,
  "editorHoverWidget.border": palette.mist.selection,
  "editorHoverWidget.foreground": palette.mist.emphasisForeground,
  "editorHoverWidget.highlightForeground": palette.mist.emphasisForeground,
  "editorHoverWidget.statusBarBackground": palette.mist.bgDark,
  "editorIndentGuide.activeBackground1": palette.mist.border,
  "editorIndentGuide.activeBackground2": palette.mist.border,
  "editorIndentGuide.activeBackground3": palette.mist.border,
  "editorIndentGuide.activeBackground4": palette.mist.border,
  "editorIndentGuide.activeBackground5": palette.mist.border,
  "editorIndentGuide.activeBackground6": palette.mist.border,
  "editorIndentGuide.background1": palette.mist.border,
  "editorIndentGuide.background2": palette.mist.border,
  "editorIndentGuide.background3": palette.mist.border,
  "editorIndentGuide.background4": palette.mist.border,
  "editorIndentGuide.background5": palette.mist.border,
  "editorIndentGuide.background6": palette.mist.border,
  "editorInfo.background": setAlpha(palette.primary.dark, opacity.subtle),
  "editorInfo.border": palette.primary.dark,
  "editorInfo.foreground": palette.primary.light,
  "editorInlayHint.background": setAlpha(palette.primary.dark, opacity.subtle),
  "editorInlayHint.foreground": palette.primary.light,
  "editorInlayHint.parameterBackground": setAlpha(palette.primary.dark, opacity.subtle),
  "editorInlayHint.parameterForeground": palette.primary.light,
  "editorInlayHint.typeBackground": setAlpha(palette.primary.dark, opacity.subtle),
  "editorInlayHint.typeForeground": palette.primary.light,
  "editorLightBulb.foreground": palette.mist.emphasisForeground,
  "editorLightBulbAi.foreground": palette.mist.emphasisForeground,
  "editorLightBulbAutoFix.foreground": palette.mist.emphasisForeground,
  "editorLineNumber.activeForeground": palette.mist.emphasisForeground,
  "editorLineNumber.dimmedForeground": palette.mist.foreground,
  "editorLineNumber.foreground": setAlpha(palette.mist.foreground, opacity.medium),
  "editorLink.activeForeground": palette.accent.blue.light,
  "editorMarkerNavigation.background": palette.mist.bgDark,
  "editorMarkerNavigationError.background": setAlpha(palette.secondary.dark, opacity.medium),
  "editorMarkerNavigationError.headerBackground": setAlpha(palette.secondary.dark, opacity.medium),
  "editorMarkerNavigationInfo.background": setAlpha(palette.primary.dark, opacity.subtle),
  "editorMarkerNavigationInfo.headerBackground": setAlpha(palette.primary.dark, opacity.subtle),
  "editorMarkerNavigationWarning.background": setAlpha(palette.accent.amber.dark, opacity.subtle),
  "editorMarkerNavigationWarning.headerBackground": setAlpha(palette.accent.amber.dark, opacity.subtle),
  "editorMinimap.inlineChatInserted": palette.git.ignored,
  "editorMultiCursor.primary.background": palette.mist.bgDark,
  "editorMultiCursor.primary.foreground": palette.mist.emphasisForeground,
  "editorMultiCursor.secondary.background": palette.mist.bgDark,
  "editorMultiCursor.secondary.foreground": palette.mist.emphasisForeground,
  "editorOverviewRuler.addedForeground": palette.accent.emerald.light,
  "editorOverviewRuler.background": palette.mist.bgDark,
  "editorOverviewRuler.border": palette.mist.selection,
  "editorOverviewRuler.bracketMatchForeground": setAlpha(palette.primary.dark, opacity.strong),
  "editorOverviewRuler.commentForeground": palette.mist.emphasisForeground,
  "editorOverviewRuler.commentUnresolvedForeground": palette.mist.emphasisForeground,
  "editorOverviewRuler.commonContentForeground": palette.mist.emphasisForeground,
  "editorOverviewRuler.currentContentForeground": palette.mist.emphasisForeground,
  "editorOverviewRuler.deletedForeground": palette.secondary.light,
  "editorOverviewRuler.errorForeground": palette.secondary.light,
  "editorOverviewRuler.findMatchForeground": setAlpha(palette.primary.dark, opacity.strong),
  "editorOverviewRuler.incomingContentForeground": palette.accent.emerald.light,
  "editorOverviewRuler.infoForeground": palette.primary.light,
  "editorOverviewRuler.inlineChatInserted": palette.git.ignored,
  "editorOverviewRuler.inlineChatRemoved": palette.git.ignored,
  "editorOverviewRuler.modifiedForeground": palette.accent.blue.light,
  "editorOverviewRuler.rangeHighlightForeground": setAlpha(palette.mist.emphasisForeground, opacity.medium),
  "editorOverviewRuler.selectionHighlightForeground": setAlpha(palette.mist.emphasisForeground, opacity.medium),
  "editorOverviewRuler.warningForeground": palette.accent.amber.light,
  "editorOverviewRuler.wordHighlightForeground": setAlpha(palette.mist.emphasisForeground, opacity.medium),
  "editorOverviewRuler.wordHighlightStrongForeground": setAlpha(palette.mist.emphasisForeground, opacity.medium),
  "editorOverviewRuler.wordHighlightTextForeground": setAlpha(palette.mist.emphasisForeground, opacity.medium),
  "editorPane.background": palette.mist.bgDark,
  "editorRuler.foreground": palette.mist.emphasisForeground,
  "editorStickyScroll.background": palette.mist.bgDark,
  "editorStickyScroll.border": palette.mist.selection,
  "editorStickyScroll.shadow": setAlpha(palette.mist.bgDark, opacity.strong),
  "editorStickyScrollHover.background": palette.mist.bgDark,
  "editorSuggestWidget.background": palette.mist.bgDark,
  "editorSuggestWidget.border": palette.mist.selection,
  "editorSuggestWidget.focusHighlightForeground": palette.mist.emphasisForeground,
  "editorSuggestWidget.foreground": palette.mist.emphasisForeground,
  "editorSuggestWidget.highlightForeground": palette.mist.emphasisForeground,
  "editorSuggestWidget.selectedBackground": setAlpha(palette.mist.bgDark, opacity.strong),
  "editorSuggestWidget.selectedForeground": palette.mist.emphasisForeground,
  "editorSuggestWidget.selectedIconForeground": palette.mist.emphasisForeground,
  "editorSuggestWidgetStatus.foreground": palette.mist.emphasisForeground,
  "editorUnicodeHighlight.background": setAlpha(palette.mist.bg, opacity.strong),
  "editorUnicodeHighlight.border": palette.mist.selection,
  "editorUnnecessaryCode.border": palette.mist.selection,
  "editorUnnecessaryCode.opacity": setAlpha(palette.mist.bgDark, opacity.strong),
  "editorWarning.background": setAlpha(palette.accent.amber.dark, opacity.subtle),
  "editorWarning.border": palette.accent.amber.dark,
  "editorWarning.foreground": palette.accent.amber.light,
  "editorWhitespace.foreground": palette.mist.emphasisForeground,
  "editorWidget.background": palette.mist.bg,
  "editorWidget.border": palette.mist.selection,
  "editorWidget.foreground": palette.mist.foreground,
  "editorWidget.resizeBorder": palette.primary.dark,
  errorForeground: palette.secondary.light,
  "extensionBadge.remoteBackground": palette.accent.blue.light,
  "extensionBadge.remoteForeground": palette.accent.blue.light,
  "extensionButton.background": palette.primary.dark,
  "extensionButton.foreground": palette.mist.emphasisForeground,
  "extensionButton.hoverBackground": palette.primary.dark,
  "extensionButton.prominentBackground": palette.primary.dark,
  "extensionButton.prominentForeground": palette.mist.emphasisForeground,
  "extensionButton.prominentHoverBackground": palette.primary.dark,
  "extensionButton.separator": palette.mist.border,
  "extensionIcon.preReleaseForeground": palette.mist.emphasisForeground,
  "extensionIcon.privateForeground": palette.mist.emphasisForeground,
  "extensionIcon.sponsorForeground": palette.mist.emphasisForeground,
  "extensionIcon.starForeground": palette.mist.emphasisForeground,
  "extensionIcon.verifiedForeground": palette.mist.emphasisForeground,
  focusBorder: palette.mist.selection,
  foreground: palette.mist.emphasisForeground,
  "git.blame.editorDecorationForeground": palette.mist.emphasisForeground,
  "gitDecoration.addedResourceForeground": palette.accent.emerald.light,
  "gitDecoration.conflictingResourceForeground": palette.accent.orange.light,
  "gitDecoration.deletedResourceForeground": palette.secondary.light,
  "gitDecoration.ignoredResourceForeground": palette.git.ignored,
  "gitDecoration.modifiedResourceForeground": palette.accent.blue.light,
  "gitDecoration.renamedResourceForeground": palette.accent.violet.dark,
  "gitDecoration.stageDeletedResourceForeground": palette.secondary.dark,
  "gitDecoration.stageModifiedResourceForeground": palette.accent.blue.dark,
  "gitDecoration.submoduleResourceForeground": palette.primary.dark,
  "gitDecoration.untrackedResourceForeground": palette.accent.emerald.dark,
  "icon.foreground": palette.git.ignored,
  "inlineChat.background": palette.mist.bg,
  "inlineChat.border": palette.mist.border,
  "inlineChat.foreground": palette.mist.emphasisForeground,
  "inlineChat.shadow": setAlpha(palette.mist.bgDark, opacity.medium),
  "inlineChatDiff.inserted": palette.git.ignored,
  "inlineChatDiff.removed": palette.git.ignored,
  "inlineChatInput.background": palette.mist.bg,
  "inlineChatInput.border": palette.mist.border,
  "inlineChatInput.focusBorder": palette.mist.border,
  "inlineChatInput.placeholderForeground": palette.mist.emphasisForeground,
  "inlineEdit.gutterIndicator.background": palette.mist.bg,
  "inlineEdit.gutterIndicator.primaryBackground": palette.mist.bg,
  "inlineEdit.gutterIndicator.primaryBorder": palette.mist.border,
  "inlineEdit.gutterIndicator.primaryForeground": palette.mist.emphasisForeground,
  "inlineEdit.gutterIndicator.secondaryBackground": palette.mist.bg,
  "inlineEdit.gutterIndicator.secondaryBorder": palette.mist.border,
  "inlineEdit.gutterIndicator.secondaryForeground": palette.mist.emphasisForeground,
  "inlineEdit.gutterIndicator.successfulBackground": setAlpha(palette.accent.emerald.dark, opacity.subtle),
  "inlineEdit.gutterIndicator.successfulBorder": palette.accent.emerald.dark,
  "inlineEdit.gutterIndicator.successfulForeground": palette.accent.emerald.light,
  "inlineEdit.modifiedBackground": setAlpha(palette.accent.blue.dark, opacity.subtle),
  "inlineEdit.modifiedBorder": palette.accent.blue.dark,
  "inlineEdit.modifiedChangedLineBackground": setAlpha(palette.accent.blue.dark, opacity.subtle),
  "inlineEdit.modifiedChangedTextBackground": setAlpha(palette.accent.blue.dark, opacity.subtle),
  "inlineEdit.originalBackground": setAlpha(palette.mist.bg, opacity.strong),
  "inlineEdit.originalBorder": palette.mist.border,
  "inlineEdit.originalChangedLineBackground": setAlpha(palette.mist.bg, opacity.medium),
  "inlineEdit.originalChangedTextBackground": setAlpha(palette.mist.bg, opacity.medium),
  "inlineEdit.tabWillAcceptModifiedBorder": palette.accent.blue.dark,
  "inlineEdit.tabWillAcceptOriginalBorder": palette.mist.border,
  "input.background": palette.mist.bgDark,
  "input.border": palette.mist.border,
  "input.foreground": palette.mist.emphasisForeground,
  "input.placeholderForeground": palette.mist.emphasisForeground,
  "inputOption.activeBackground": palette.mist.bg,
  "inputOption.activeBorder": palette.mist.border,
  "inputOption.activeForeground": palette.mist.emphasisForeground,
  "inputOption.hoverBackground": palette.mist.bg,
  "inputValidation.errorBackground": setAlpha(palette.secondary.dark, opacity.medium),
  "inputValidation.errorBorder": palette.secondary.dark,
  "inputValidation.errorForeground": palette.secondary.light,
  "inputValidation.infoBackground": setAlpha(palette.primary.dark, opacity.subtle),
  "inputValidation.infoBorder": palette.primary.dark,
  "inputValidation.infoForeground": palette.primary.light,
  "inputValidation.warningBackground": setAlpha(palette.accent.amber.dark, opacity.subtle),
  "inputValidation.warningBorder": palette.accent.amber.dark,
  "inputValidation.warningForeground": palette.accent.amber.light,
  "interactive.activeCodeBorder": palette.mist.border,
  "interactive.inactiveCodeBorder": palette.mist.border,
  "keybindingLabel.background": palette.mist.bg,
  "keybindingLabel.border": palette.git.ignored,
  "keybindingLabel.bottomBorder": palette.git.ignored,
  "keybindingLabel.foreground": palette.mist.emphasisForeground,
  "keybindingTable.headerBackground": palette.mist.bg,
  "keybindingTable.rowsBackground": palette.mist.bg,
  "list.activeSelectionBackground": palette.mist.border,
  "list.activeSelectionForeground": palette.mist.emphasisForeground,
  "list.activeSelectionIconForeground": palette.mist.emphasisForeground,
  "list.deemphasizedForeground": palette.mist.emphasisForeground,
  "list.dropBackground": palette.mist.border,
  "list.dropBetweenBackground": palette.mist.border,
  "list.errorForeground": palette.secondary.light,
  "list.filterMatchBackground": setAlpha(palette.primary.dark, opacity.medium),
  "list.filterMatchBorder": palette.primary.dark,
  "list.focusAndSelectionOutline": palette.git.ignored,
  "list.focusBackground": palette.mist.border,
  "list.focusForeground": palette.mist.emphasisForeground,
  "list.focusHighlightForeground": palette.mist.emphasisForeground,
  "list.focusOutline": palette.git.ignored,
  "list.highlightForeground": palette.primary.dark,
  "list.hoverBackground": palette.mist.border,
  "list.hoverForeground": palette.mist.emphasisForeground,
  "list.inactiveFocusBackground": palette.mist.border,
  "list.inactiveFocusOutline": palette.git.ignored,
  "list.inactiveSelectionBackground": palette.mist.border,
  "list.inactiveSelectionForeground": palette.mist.foreground,
  "list.inactiveSelectionIconForeground": palette.mist.emphasisForeground,
  "list.invalidItemForeground": palette.mist.emphasisForeground,
  "list.warningForeground": palette.accent.amber.light,
  "listFilterWidget.background": palette.mist.bg,
  "listFilterWidget.noMatchesOutline": palette.git.ignored,
  "listFilterWidget.outline": palette.git.ignored,
  "listFilterWidget.shadow": setAlpha(palette.mist.bgDark, opacity.medium),
  "menu.background": palette.mist.bg,
  "menu.border": palette.mist.border,
  "menu.foreground": palette.mist.emphasisForeground,
  "menu.selectionBackground": palette.mist.bg,
  "menu.selectionBorder": palette.mist.border,
  "menu.selectionForeground": palette.mist.emphasisForeground,
  "menu.separatorBackground": palette.mist.bg,
  "menubar.selectionBackground": palette.mist.bg,
  "menubar.selectionBorder": palette.mist.border,
  "menubar.selectionForeground": palette.mist.emphasisForeground,
  "merge.border": palette.mist.border,
  "merge.commonContentBackground": setAlpha(palette.mist.bg, opacity.medium),
  "merge.commonHeaderBackground": setAlpha(palette.mist.bg, opacity.medium),
  "merge.currentContentBackground": setAlpha(palette.mist.bg, opacity.medium),
  "merge.currentHeaderBackground": setAlpha(palette.mist.bg, opacity.medium),
  "merge.incomingContentBackground": setAlpha(palette.accent.emerald.dark, opacity.subtle),
  "merge.incomingHeaderBackground": setAlpha(palette.accent.emerald.dark, opacity.subtle),
  "mergeEditor.change.background": palette.mist.bg,
  "mergeEditor.change.word.background": palette.mist.bg,
  "mergeEditor.changeBase.background": palette.mist.bg,
  "mergeEditor.changeBase.word.background": palette.mist.bg,
  "mergeEditor.conflict.handled.minimapOverViewRuler": palette.accent.orange.light,
  "mergeEditor.conflict.handledFocused.border": palette.accent.orange.light,
  "mergeEditor.conflict.handledUnfocused.border": palette.accent.orange.light,
  "mergeEditor.conflict.input1.background": palette.accent.orange.light,
  "mergeEditor.conflict.input2.background": palette.accent.orange.light,
  "mergeEditor.conflict.unhandled.minimapOverViewRuler": palette.accent.orange.light,
  "mergeEditor.conflict.unhandledFocused.border": palette.accent.orange.light,
  "mergeEditor.conflict.unhandledUnfocused.border": palette.accent.orange.light,
  "mergeEditor.conflictingLines.background": palette.accent.orange.light,
  "minimap.background": setAlpha(palette.mist.bgDark, opacity.opaque),
  "minimap.chatEditHighlight": palette.git.ignored,
  "minimap.errorHighlight": palette.secondary.light,
  "minimap.findMatchHighlight": setAlpha(palette.primary.dark, opacity.strong),
  "minimap.foregroundOpacity": setAlpha(palette.mist.foreground, opacity.strong),
  "minimap.infoHighlight": palette.primary.light,
  "minimap.selectionHighlight": setAlpha(palette.primary.dark, opacity.medium),
  "minimap.selectionOccurrenceHighlight": setAlpha(palette.primary.dark, opacity.medium),
  "minimap.warningHighlight": palette.accent.amber.light,
  "minimapGutter.addedBackground": setAlpha(palette.accent.emerald.dark, opacity.subtle),
  "minimapGutter.deletedBackground": setAlpha(palette.secondary.dark, opacity.medium),
  "minimapGutter.modifiedBackground": setAlpha(palette.accent.blue.dark, opacity.subtle),
  "minimapSlider.activeBackground": palette.mist.bg,
  "minimapSlider.background": palette.mist.bg,
  "minimapSlider.hoverBackground": palette.mist.bg,
  "multiDiffEditor.background": palette.mist.bg,
  "multiDiffEditor.border": palette.mist.border,
  "multiDiffEditor.headerBackground": palette.mist.bg,
  "notebook.cellBorderColor": palette.git.ignored,
  "notebook.cellEditorBackground": palette.mist.bg,
  "notebook.cellHoverBackground": palette.mist.bg,
  "notebook.cellInsertionIndicator": palette.git.ignored,
  "notebook.cellStatusBarItemHoverBackground": palette.mist.bg,
  "notebook.cellToolbarSeparator": palette.git.ignored,
  "notebook.editorBackground": palette.mist.bg,
  "notebook.focusedCellBackground": palette.mist.bg,
  "notebook.focusedCellBorder": palette.mist.border,
  "notebook.focusedEditorBorder": palette.mist.border,
  "notebook.inactiveFocusedCellBorder": palette.mist.border,
  "notebook.inactiveSelectedCellBorder": palette.mist.border,
  "notebook.outputContainerBackgroundColor": palette.git.ignored,
  "notebook.outputContainerBorderColor": palette.git.ignored,
  "notebook.selectedCellBackground": palette.mist.bg,
  "notebook.selectedCellBorder": palette.mist.border,
  "notebook.symbolHighlightBackground": palette.mist.bg,
  "notebookEditorOverviewRuler.runningCellForeground": palette.mist.emphasisForeground,
  "notebookScrollbarSlider.activeBackground": setAlpha(palette.mist.border, opacity.strong),
  "notebookScrollbarSlider.background": setAlpha(palette.mist.border, opacity.strong),
  "notebookScrollbarSlider.hoverBackground": setAlpha(palette.mist.border, opacity.strong),
  "notebookStatusErrorIcon.foreground": palette.secondary.light,
  "notebookStatusRunningIcon.foreground": palette.mist.emphasisForeground,
  "notebookStatusSuccessIcon.foreground": palette.accent.emerald.light,
  "notificationCenter.border": palette.mist.border,
  "notificationCenterHeader.background": palette.mist.bg,
  "notificationCenterHeader.foreground": palette.mist.emphasisForeground,
  "notificationLink.foreground": palette.accent.blue.light,
  "notifications.background": palette.mist.bg,
  "notifications.border": palette.mist.border,
  "notifications.foreground": palette.mist.emphasisForeground,
  "notificationsErrorIcon.foreground": palette.secondary.light,
  "notificationsInfoIcon.foreground": palette.primary.light,
  "notificationsWarningIcon.foreground": palette.accent.amber.light,
  "notificationToast.border": palette.mist.border,
  "outputView.background": palette.mist.bg,
  "outputViewStickyScroll.background": palette.mist.bg,
  "panel.background": palette.mist.bg,
  "panel.border": palette.mist.border,
  "panel.dropBorder": palette.mist.border,
  "panelInput.border": palette.mist.border,
  "panelSection.border": palette.mist.border,
  "panelSection.dropBackground": palette.mist.bg,
  "panelSectionHeader.background": palette.mist.bg,
  "panelSectionHeader.border": palette.mist.border,
  "panelSectionHeader.foreground": palette.mist.emphasisForeground,
  "panelStickyScroll.background": palette.mist.bg,
  "panelStickyScroll.border": palette.mist.border,
  "panelStickyScroll.shadow": setAlpha(palette.mist.bgDark, opacity.medium),
  "panelTitle.activeBorder": palette.mist.border,
  "panelTitle.activeForeground": palette.mist.emphasisForeground,
  "panelTitle.border": palette.mist.border,
  "panelTitle.inactiveForeground": palette.mist.emphasisForeground,
  "panelTitleBadge.background": palette.mist.bg,
  "panelTitleBadge.foreground": palette.mist.emphasisForeground,
  "peekView.border": palette.mist.border,
  "peekViewEditor.background": palette.mist.bg,
  "peekViewEditor.matchHighlightBackground": setAlpha(palette.primary.dark, opacity.medium),
  "peekViewEditor.matchHighlightBorder": setAlpha(palette.primary.dark, opacity.medium),
  "peekViewEditorGutter.background": palette.mist.bg,
  "peekViewEditorStickyScroll.background": palette.mist.bg,
  "peekViewResult.background": palette.mist.bg,
  "peekViewResult.fileForeground": palette.mist.emphasisForeground,
  "peekViewResult.lineForeground": palette.mist.emphasisForeground,
  "peekViewResult.matchHighlightBackground": setAlpha(palette.primary.dark, opacity.medium),
  "peekViewResult.selectionBackground": palette.mist.bg,
  "peekViewResult.selectionForeground": palette.mist.emphasisForeground,
  "peekViewTitle.background": palette.mist.bg,
  "peekViewTitleDescription.foreground": palette.mist.emphasisForeground,
  "peekViewTitleLabel.foreground": palette.mist.emphasisForeground,
  "pickerGroup.border": palette.mist.border,
  "pickerGroup.foreground": palette.mist.emphasisForeground,
  "ports.iconRunningProcessForeground": palette.mist.emphasisForeground,
  "problemsErrorIcon.foreground": palette.secondary.light,
  "problemsInfoIcon.foreground": palette.primary.light,
  "problemsWarningIcon.foreground": palette.accent.amber.light,
  "profileBadge.background": palette.mist.bg,
  "profileBadge.foreground": palette.mist.emphasisForeground,
  "profiles.sashBorder": palette.mist.border,
  "progressBar.background": palette.mist.bg,
  "quickInput.background": palette.mist.bg,
  "quickInput.foreground": palette.mist.emphasisForeground,
  "quickInputList.focusBackground": palette.mist.bg,
  "quickInputList.focusForeground": palette.mist.emphasisForeground,
  "quickInputList.focusIconForeground": palette.mist.emphasisForeground,
  "quickInputTitle.background": palette.mist.bg,
  "radio.activeBackground": palette.mist.bg,
  "radio.activeBorder": palette.mist.border,
  "radio.activeForeground": palette.mist.emphasisForeground,
  "radio.inactiveBackground": palette.mist.bg,
  "radio.inactiveBorder": palette.mist.border,
  "radio.inactiveForeground": palette.mist.emphasisForeground,
  "radio.inactiveHoverBackground": palette.mist.bg,
  "sash.hoverBorder": palette.mist.border,
  "scmGraph.foreground1": palette.git.ignored,
  "scmGraph.foreground2": palette.git.ignored,
  "scmGraph.foreground3": palette.git.ignored,
  "scmGraph.foreground4": palette.git.ignored,
  "scmGraph.foreground5": palette.git.ignored,
  "scmGraph.historyItemBaseRefColor": palette.git.ignored,
  "scmGraph.historyItemHoverAdditionsForeground": palette.mist.emphasisForeground,
  "scmGraph.historyItemHoverDefaultLabelBackground": palette.mist.bg,
  "scmGraph.historyItemHoverDefaultLabelForeground": palette.mist.emphasisForeground,
  "scmGraph.historyItemHoverDeletionsForeground": palette.mist.emphasisForeground,
  "scmGraph.historyItemHoverLabelForeground": palette.mist.emphasisForeground,
  "scmGraph.historyItemRefColor": palette.git.ignored,
  "scmGraph.historyItemRemoteRefColor": palette.accent.blue.light,
  "scrollbar.shadow": setAlpha(palette.mist.bgDark, opacity.transparent),
  "scrollbarSlider.activeBackground": palette.mist.bg,
  "scrollbarSlider.background": setAlpha(palette.mist.border, opacity.subtle),
  "scrollbarSlider.hoverBackground": palette.mist.bg,
  "search.resultsInfoForeground": palette.primary.light,
  "searchEditor.findMatchBackground": setAlpha(palette.primary.dark, opacity.medium),
  "searchEditor.findMatchBorder": palette.primary.dark,
  "searchEditor.textInputBorder": palette.primary.dark,
  "selection.background": setAlpha(palette.mist.selection, opacity.strong),
  "settings.checkboxBackground": palette.mist.bgDark,
  "settings.checkboxBorder": palette.mist.border,
  "settings.checkboxForeground": palette.mist.emphasisForeground,
  "settings.dropdownBackground": palette.mist.bgDark,
  "settings.dropdownBorder": palette.mist.border,
  "settings.dropdownForeground": palette.mist.emphasisForeground,
  "settings.dropdownListBorder": palette.mist.border,
  "settings.focusedRowBackground": palette.mist.bgDark,
  "settings.focusedRowBorder": palette.mist.border,
  "settings.headerBorder": palette.mist.border,
  "settings.headerForeground": palette.mist.emphasisForeground,
  "settings.modifiedItemIndicator": palette.git.ignored,
  "settings.numberInputBackground": palette.mist.bgDark,
  "settings.numberInputBorder": palette.mist.border,
  "settings.numberInputForeground": palette.mist.emphasisForeground,
  "settings.rowHoverBackground": palette.mist.bgDark,
  "settings.sashBorder": palette.mist.border,
  "settings.settingsHeaderHoverForeground": palette.mist.emphasisForeground,
  "settings.textInputBackground": palette.mist.bgDark,
  "settings.textInputBorder": palette.mist.border,
  "settings.textInputForeground": palette.mist.emphasisForeground,
  "sideBar.background": palette.mist.bg,
  "sideBar.border": palette.mist.border,
  "sideBar.dropBackground": palette.mist.bg,
  "sideBar.foreground": palette.mist.foreground,
  "sideBarActivityBarTop.border": palette.mist.border,
  "sideBarSectionHeader.background": palette.mist.bg,
  "sideBarSectionHeader.border": palette.mist.border,
  "sideBarSectionHeader.foreground": palette.mist.foreground,
  "sideBarStickyScroll.background": palette.mist.bg,
  "sideBarStickyScroll.border": palette.mist.border,
  "sideBarStickyScroll.shadow": setAlpha(palette.mist.bgDark, opacity.medium),
  "sideBarTitle.background": palette.mist.bg,
  "sideBarTitle.border": palette.mist.border,
  "sideBarTitle.foreground": palette.mist.emphasisForeground,
  "sideBySideEditor.horizontalBorder": palette.mist.border,
  "sideBySideEditor.verticalBorder": palette.mist.border,
  "simpleFindWidget.sashBorder": palette.primary.dark,
  "statusBar.background": palette.mist.bg,
  "statusBar.border": palette.mist.border,
  "statusBar.debuggingBackground": palette.mist.bg,
  "statusBar.debuggingBorder": palette.mist.border,
  "statusBar.debuggingForeground": palette.mist.emphasisForeground,
  "statusBar.focusBorder": palette.mist.border,
  "statusBar.foreground": palette.mist.foreground,
  "statusBar.noFolderBackground": palette.mist.bg,
  "statusBar.noFolderBorder": palette.mist.border,
  "statusBar.noFolderForeground": palette.mist.foreground,
  "statusBarItem.activeBackground": palette.mist.bg,
  "statusBarItem.compactHoverBackground": palette.mist.bg,
  "statusBarItem.errorBackground": setAlpha(palette.secondary.dark, opacity.medium),
  "statusBarItem.errorForeground": palette.secondary.light,
  "statusBarItem.errorHoverBackground": setAlpha(palette.secondary.dark, opacity.medium),
  "statusBarItem.errorHoverForeground": palette.secondary.light,
  "statusBarItem.focusBorder": palette.mist.border,
  "statusBarItem.hoverBackground": palette.mist.bg,
  "statusBarItem.hoverForeground": palette.mist.emphasisForeground,
  "statusBarItem.offlineBackground": palette.mist.bg,
  "statusBarItem.offlineForeground": palette.mist.emphasisForeground,
  "statusBarItem.offlineHoverBackground": palette.mist.bg,
  "statusBarItem.offlineHoverForeground": palette.mist.emphasisForeground,
  "statusBarItem.prominentBackground": palette.mist.bg,
  "statusBarItem.prominentForeground": palette.mist.emphasisForeground,
  "statusBarItem.prominentHoverBackground": palette.mist.bg,
  "statusBarItem.prominentHoverForeground": palette.mist.emphasisForeground,
  "statusBarItem.remoteBackground": palette.accent.blue.light,
  "statusBarItem.remoteForeground": palette.accent.blue.light,
  "statusBarItem.remoteHoverBackground": palette.accent.blue.light,
  "statusBarItem.remoteHoverForeground": palette.accent.blue.light,
  "statusBarItem.warningBackground": setAlpha(palette.accent.amber.dark, opacity.subtle),
  "statusBarItem.warningForeground": palette.accent.amber.light,
  "statusBarItem.warningHoverBackground": setAlpha(palette.accent.amber.dark, opacity.subtle),
  "statusBarItem.warningHoverForeground": palette.accent.amber.light,
  "symbolIcon.arrayForeground": palette.accent.violet.light,
  "symbolIcon.booleanForeground": palette.accent.violet.light,
  "symbolIcon.classForeground": palette.accent.violet.light,
  "symbolIcon.colorForeground": palette.accent.violet.light,
  "symbolIcon.constantForeground": palette.accent.violet.light,
  "symbolIcon.constructorForeground": palette.accent.violet.light,
  "symbolIcon.enumeratorForeground": palette.accent.violet.light,
  "symbolIcon.enumeratorMemberForeground": palette.accent.violet.light,
  "symbolIcon.eventForeground": palette.accent.violet.light,
  "symbolIcon.fieldForeground": palette.accent.violet.light,
  "symbolIcon.fileForeground": palette.accent.violet.light,
  "symbolIcon.folderForeground": palette.accent.violet.light,
  "symbolIcon.functionForeground": palette.accent.violet.light,
  "symbolIcon.interfaceForeground": palette.accent.violet.light,
  "symbolIcon.keyForeground": palette.accent.violet.light,
  "symbolIcon.keywordForeground": palette.accent.violet.light,
  "symbolIcon.methodForeground": palette.accent.violet.light,
  "symbolIcon.moduleForeground": palette.accent.violet.light,
  "symbolIcon.namespaceForeground": palette.accent.violet.light,
  "symbolIcon.nullForeground": palette.accent.violet.light,
  "symbolIcon.numberForeground": palette.accent.violet.light,
  "symbolIcon.objectForeground": palette.accent.violet.light,
  "symbolIcon.operatorForeground": palette.accent.violet.light,
  "symbolIcon.packageForeground": palette.accent.violet.light,
  "symbolIcon.propertyForeground": palette.accent.violet.light,
  "symbolIcon.referenceForeground": palette.accent.violet.light,
  "symbolIcon.snippetForeground": palette.accent.violet.light,
  "symbolIcon.stringForeground": palette.accent.violet.light,
  "symbolIcon.structForeground": palette.accent.violet.light,
  "symbolIcon.textForeground": palette.accent.violet.light,
  "symbolIcon.typeParameterForeground": palette.accent.violet.light,
  "symbolIcon.unitForeground": palette.accent.violet.light,
  "symbolIcon.variableForeground": palette.accent.violet.light,
  "tab.activeBackground": palette.mist.bgDark,
  "tab.activeBorder": palette.mist.bgDark,
  "tab.activeBorderTop": palette.primary.dark,
  "tab.activeForeground": palette.mist.emphasisForeground,
  "tab.activeModifiedBorder": palette.accent.blue.dark,
  "tab.border": palette.mist.border,
  "tab.dragAndDropBorder": palette.mist.border,
  "tab.hoverBackground": palette.mist.bg,
  "tab.hoverBorder": palette.mist.border,
  "tab.hoverForeground": palette.mist.foreground,
  "tab.inactiveBackground": palette.mist.bg,
  "tab.inactiveForeground": palette.mist.foreground,
  "tab.inactiveModifiedBorder": palette.accent.blue.dark,
  "tab.lastPinnedBorder": palette.mist.border,
  "tab.selectedBackground": palette.mist.bg,
  "tab.selectedBorderTop": palette.mist.border,
  "tab.selectedForeground": palette.mist.foreground,
  "tab.unfocusedActiveBackground": palette.mist.bgDark,
  "tab.unfocusedActiveBorder": palette.mist.bgDark,
  "tab.unfocusedActiveBorderTop": palette.mist.bgDark,
  "tab.unfocusedActiveForeground": palette.mist.emphasisForeground,
  "tab.unfocusedActiveModifiedBorder": palette.accent.blue.dark,
  "tab.unfocusedHoverBackground": palette.mist.bg,
  "tab.unfocusedHoverBorder": palette.mist.border,
  "tab.unfocusedHoverForeground": palette.mist.foreground,
  "tab.unfocusedInactiveBackground": palette.mist.bgDark,
  "tab.unfocusedInactiveForeground": palette.mist.emphasisForeground,
  "tab.unfocusedInactiveModifiedBorder": palette.accent.blue.dark,
  "terminal.ansiBlack": palette.mist.bgDark,
  "terminal.ansiBlue": palette.accent.blue.dark,
  "terminal.ansiBrightBlack": palette.mist.border,
  "terminal.ansiBrightBlue": palette.accent.blue.light,
  "terminal.ansiBrightCyan": palette.primary.light,
  "terminal.ansiBrightGreen": palette.accent.emerald.light,
  "terminal.ansiBrightMagenta": palette.accent.violet.light,
  "terminal.ansiBrightRed": palette.secondary.light,
  "terminal.ansiBrightWhite": palette.mist.emphasisForeground,
  "terminal.ansiBrightYellow": palette.accent.amber.light,
  "terminal.ansiCyan": palette.primary.dark,
  "terminal.ansiGreen": palette.accent.emerald.dark,
  "terminal.ansiMagenta": palette.accent.violet.dark,
  "terminal.ansiRed": palette.secondary.dark,
  "terminal.ansiWhite": palette.mist.foreground,
  "terminal.ansiYellow": palette.accent.amber.dark,
  "terminal.background": palette.mist.bgDark,
  "terminal.border": palette.mist.border,
  "terminal.dropBackground": setAlpha(palette.mist.bgDark, opacity.medium),
  "terminal.findMatchBackground": setAlpha(palette.primary.dark, opacity.medium),
  "terminal.findMatchBorder": palette.primary.dark,
  "terminal.findMatchHighlightBackground": setAlpha(palette.primary.dark, opacity.medium),
  "terminal.findMatchHighlightBorder": setAlpha(palette.primary.dark, opacity.medium),
  "terminal.foreground": palette.mist.emphasisForeground,
  "terminal.hoverHighlightBackground": setAlpha(palette.mist.bgDark, opacity.medium),
  "terminal.inactiveSelectionBackground": palette.mist.bgDark,
  "terminal.initialHintForeground": palette.mist.emphasisForeground,
  "terminal.selectionBackground": palette.mist.bgDark,
  "terminal.selectionForeground": palette.mist.emphasisForeground,
  "terminal.tab.activeBorder": palette.mist.border,
  "terminalCommandDecoration.defaultBackground": palette.mist.bg,
  "terminalCommandDecoration.errorBackground": setAlpha(palette.secondary.dark, opacity.medium),
  "terminalCommandDecoration.successBackground": setAlpha(palette.accent.emerald.dark, opacity.subtle),
  "terminalCommandGuide.foreground": palette.mist.emphasisForeground,
  "terminalCursor.background": palette.mist.bg,
  "terminalCursor.foreground": palette.mist.emphasisForeground,
  "terminalOverviewRuler.border": palette.mist.border,
  "terminalOverviewRuler.cursorForeground": palette.mist.emphasisForeground,
  "terminalOverviewRuler.findMatchForeground": setAlpha(palette.primary.dark, opacity.strong),
  "terminalStickyScroll.background": palette.mist.bg,
  "terminalStickyScroll.border": palette.mist.border,
  "terminalStickyScrollHover.background": palette.mist.bg,
  "terminalSymbolIcon.aliasForeground": palette.accent.violet.light,
  "terminalSymbolIcon.argumentForeground": palette.accent.violet.light,
  "terminalSymbolIcon.fileForeground": palette.accent.violet.light,
  "terminalSymbolIcon.flagForeground": palette.accent.violet.light,
  "terminalSymbolIcon.folderForeground": palette.accent.violet.light,
  "terminalSymbolIcon.inlineSuggestionForeground": palette.accent.violet.light,
  "terminalSymbolIcon.methodForeground": palette.accent.violet.light,
  "terminalSymbolIcon.optionForeground": palette.accent.violet.light,
  "terminalSymbolIcon.optionValueForeground": palette.accent.violet.light,
  "testing.coverCountBadgeBackground": setAlpha(palette.mist.border, opacity.strong),
  "testing.coverCountBadgeForeground": palette.mist.emphasisForeground,
  "testing.coveredBackground": setAlpha(palette.accent.emerald.dark, opacity.subtle),
  "testing.coveredBorder": palette.accent.emerald.dark,
  "testing.coveredGutterBackground": setAlpha(palette.accent.emerald.dark, opacity.subtle),
  "testing.iconErrored": palette.secondary.light,
  "testing.iconErrored.retired": palette.secondary.light,
  "testing.iconFailed": palette.secondary.light,
  "testing.iconFailed.retired": palette.secondary.light,
  "testing.iconPassed": palette.accent.emerald.light,
  "testing.iconPassed.retired": palette.accent.emerald.light,
  "testing.iconQueued": palette.accent.amber.light,
  "testing.iconQueued.retired": palette.accent.amber.light,
  "testing.iconSkipped": palette.accent.amber.light,
  "testing.iconSkipped.retired": palette.accent.amber.light,
  "testing.iconUnset": palette.git.ignored,
  "testing.iconUnset.retired": palette.git.ignored,
  "testing.message.error.badgeBackground": setAlpha(palette.secondary.dark, opacity.medium),
  "testing.message.error.badgeBorder": palette.secondary.dark,
  "testing.message.error.badgeForeground": palette.secondary.light,
  "testing.message.error.lineBackground": setAlpha(palette.secondary.dark, opacity.medium),
  "testing.message.info.decorationForeground": palette.primary.light,
  "testing.message.info.lineBackground": setAlpha(palette.primary.dark, opacity.subtle),
  "testing.messagePeekBorder": palette.mist.border,
  "testing.messagePeekHeaderBackground": setAlpha(palette.mist.border, opacity.strong),
  "testing.peekBorder": palette.mist.border,
  "testing.peekHeaderBackground": setAlpha(palette.mist.border, opacity.strong),
  "testing.runAction": palette.git.ignored,
  "testing.uncoveredBackground": setAlpha(palette.accent.emerald.dark, opacity.subtle),
  "testing.uncoveredBorder": palette.accent.emerald.dark,
  "testing.uncoveredBranchBackground": setAlpha(palette.accent.emerald.dark, opacity.subtle),
  "testing.uncoveredGutterBackground": setAlpha(palette.accent.emerald.dark, opacity.subtle),
  "textBlockQuote.background": palette.mist.bg,
  "textBlockQuote.border": palette.mist.border,
  "textCodeBlock.background": palette.mist.bg,
  "textLink.activeForeground": palette.accent.blue.light,
  "textLink.foreground": palette.accent.blue.light,
  "textPreformat.background": palette.mist.bg,
  "textPreformat.foreground": palette.mist.emphasisForeground,
  "textSeparator.foreground": palette.mist.emphasisForeground,
  "titleBar.activeBackground": palette.mist.bg,
  "titleBar.activeForeground": palette.mist.foreground,
  "titleBar.border": palette.mist.border,
  "titleBar.inactiveBackground": palette.mist.bg,
  "titleBar.inactiveForeground": palette.mist.foreground,
  "toolbar.activeBackground": palette.mist.bg,
  "toolbar.hoverBackground": palette.mist.bg,
  "toolbar.hoverOutline": palette.git.ignored,
  "tree.inactiveIndentGuidesStroke": palette.mist.border,
  "tree.indentGuidesStroke": palette.mist.border,
  "tree.tableColumnsBorder": palette.mist.border,
  "tree.tableOddRowsBackground": palette.mist.border,
  "walkThrough.embeddedEditorBackground": palette.mist.bgDark,
  "walkthrough.stepTitle.foreground": palette.mist.emphasisForeground,
  "welcomePage.background": palette.mist.bgDark,
  "welcomePage.progress.background": palette.mist.bgDark,
  "welcomePage.progress.foreground": palette.mist.emphasisForeground,
  "welcomePage.tileBackground": palette.mist.bgDark,
  "welcomePage.tileBorder": palette.mist.border,
  "welcomePage.tileHoverBackground": palette.mist.bgDark,
  "widget.border": palette.mist.border,
  "widget.shadow": setAlpha(palette.mist.bgDark, opacity.strong),
  "window.activeBorder": palette.mist.border,
  "window.inactiveBorder": palette.mist.border,
};

const semanticTokenColors: SemanticTokenColors = {};

const tokenColors: TokenColors = [
  {
    name: "Comment",
    scope: ["comment", "comment.line", "comment.block"],
    settings: { foreground: palette.mist.selection, fontStyle: "bold italic" },
  },
  {
    name: "Keyword",
    scope: ["keyword.control", "keyword.operator.new"],
    settings: { foreground: palette.accent.cyan.light },
  },
  {
    name: "Storage",
    scope: ["storage.type", "storage.modifier"],
    settings: { foreground: palette.accent.cyan.light },
  },
  {
    name: "Function",
    scope: ["entity.name.function", "entity.name.method"],
    settings: { foreground: palette.accent.orange.light },
  },
  {
    name: "Class",
    scope: ["entity.name.class", "entity.name.type", "meta.class", "meta.type"],
    settings: { foreground: palette.accent.orange.light },
  },
  {
    name: "Variable",
    scope: ["variable"],
    settings: { foreground: palette.accent.violet.light },
  },
  {
    name: "Literal",
    scope: ["string"],
    settings: { foreground: palette.accent.emerald.light },
  },
  {
    name: "Constant",
    scope: ["constant"],
    settings: { foreground: palette.accent.rose.light },
  },
  {
    name: "JSX Component",
    scope: ["support.class.component"],
    settings: { foreground: palette.accent.orange.light },
  },
  {
    name: "JSX HTML Tags",
    scope: ["entity.name.tag"],
    settings: { foreground: palette.accent.cyan.light },
  },
  {
    name: "JSX Attributes",
    scope: ["entity.other.attribute-name"],
    settings: { foreground: palette.accent.violet.light },
  },
  {
    name: "JSX Strings",
    scope: ["string.quoted.double"],
    settings: { foreground: palette.accent.emerald.light },
  },
  {
    name: "JSX Brackets",
    scope: ["punctuation.definition.tag.begin", "punctuation.definition.tag.end"],
    settings: { foreground: palette.accent.cyan.light },
  },
  {
    name: "JSON Keys",
    scope: ["support.type.property-name.json"],
    settings: { foreground: palette.accent.violet.light },
  },

  {
    name: "Markdown Headings",
    scope: ["markup.heading.markdown"],
    settings: { foreground: palette.mist.emphasisForeground, fontStyle: "bold" },
  },
  {
    name: "Markdown Bold",
    scope: ["markup.bold.markdown"],
    settings: { fontStyle: "bold" },
  },
  {
    name: "Markdown Italic",
    scope: ["markup.italic.markdown"],
    settings: { fontStyle: "italic" },
  },
  {
    name: "Markdown Links",
    scope: ["markup.underline.link.markdown"],
    settings: { foreground: palette.accent.cyan.light, fontStyle: "underline" },
  },
  {
    name: "Markdown Inline Code",
    scope: ["markup.inline.raw.string.markdown"],
    settings: { foreground: palette.accent.rose.light },
  },
  {
    name: "Markdown Code Block",
    scope: ["markup.fenced_code.block.markdown"],
    settings: { foreground: palette.accent.rose.light },
  },
  {
    name: "Markdown Quotes",
    scope: ["markup.quote.markdown"],
    settings: { foreground: palette.accent.emerald.light, fontStyle: "italic" },
  },
  {
    name: "Markdown Separator",
    scope: ["meta.separator.markdown"],
    settings: { foreground: palette.mist.foreground },
  },
  {
    scope: ["text", "source"],
    settings: { foreground: palette.mist.foreground },
  },
];

const theme: Theme = {
  name: "Tailwind Mist",
  colors,
  tokenColors,
  semanticTokenColors: semanticTokenColors,
  semanticHighlighting: true,
};

console.log("writing theme to themes/Tailwind Mist-color-theme.json");
await writeFile("themes/Tailwind Mist-color-theme.json", JSON.stringify(theme, null, 2));
